### ISSUE TITLE
Crash on starting new singleplayer world, might be mod conflict?

### ISSUE THREAD

**Issue by katubug** [samedifferent/TrickOrTreat#2]
Hello! I'm testing this mod in my fabric modpack, and encountered this crash upon starting a new Singleplayer world: https://pastebin.com/ncVLCUcx

Artifacts: 5.0.2
Trick or Treat: 1.0.0
Fabric: 0.11.7

Since it looked like a mod conflict, I then disabled Artifacts and loaded into a new singleplayer world, and got this crash: https://pastebin.com/272kn8wG

No idea if they're related, but let me know if you need any more information from me!

**Comment by katubug** [comment]
Sorry, does this mean it's an unfixable incompatibility? I'm not sure whether I should adjust my modlist or not.

**Comment by samedifferent** [comment]
Unfortunately, Lithium has a bad reputation of causing issues with mob AI. This incompatibility occurs with so many other mods, not just this one. It is best for players to add performance-enhancing mods on their own, at their own risk.

**Comment by katubug** [comment]
That's understandable. I don't mind removing it, I just wasn't sure how to
interpret the issue being closed, so wanted to clarify. :) Thanks!

**Comment by samedifferent** [comment]
The bug has been fixed in version 1.0.1. You can now use lithium with the mod.
