### ISSUE TITLE
unable join new or exisiting world with mod included.[Bug]: 

### ISSUE THREAD

**Issue by TheRanker** [samedifferent/TrickOrTreat#5]
### Mod Version

trickortreat-FABRIC-1.17.1-1.0.0.jar

### Mod Loader

Fabric

### Mod Loader Version

0.11.7

### What happened?

crash on world load.. wihtout fail. 100% of the time

in my modpack im creating, with 220 mods. 

### latest.log

[latest.log](https://github.com/samedifferent/TrickOrTreat/files/7393041/latest.log)

**Comment by samedifferent** [comment]
Lithium has buggy interactions with AI. Please try removing Lithium.

**Comment by TheRanker** [comment]
I'll remove ur mod before I remove lithium. GL competing against lithium

**Comment by Jamalam360** [comment]
This is fixed in version 1.0.1
