### ISSUE TITLE
[Bug]:Crash with lithium installed

### ISSUE THREAD

**Issue by JustAPieGuy** [samedifferent/TrickOrTreat#6]
### Mod Version

1.0.0

### Mod Loader

Fabric

### Mod Loader Version

0.11.7

### What happened?

When entering/creating a world with lithium installed game crashes.

### latest.log

[latest.log](https://github.com/samedifferent/TrickOrTreat/files/7394803/latest.log)

**Comment by Jamalam360** [comment]
This is fixed in version 1.0.1
